include:
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/credential-check
    ref: 2.3.2
    file: ci-include-credential-check-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/fragment-version-check
    ref: 2.4.7
    file: ci-include-fragment-version-check-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/required-fragment-check
    ref: 2.17.2
    file: ci-include-required-fragment-check-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/update-semver
    ref: 5.1.1
    file: ci-include-update-semver-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/gitleaks
    ref: 3.2.1
    file: ci-include-gitleaks-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/shell-check
    ref: 4.0.3
    file: ci-include-shell-check-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/todo-checker
    ref: 2.1.5
    file: ci-include-todo-checker-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/es-lint
    ref: 4.0.2
    file: ci-include-es-lint-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/docker-lint
    ref: 2.5.2
    file: ci-include-docker-lint-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/node-unit-test
    ref: 2.4.0
    file: ci-include-node-unit-test-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/node-nyc-test-coverage
    ref: 4.1.0
    file: ci-nyc-test-coverage-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/node-stryker-mutation
    ref: 3.24.1
    file: ci-include-node-stryker-mutation-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/node-audit
    ref: 3.1.2
    file: ci-include-node-audit-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/node-outdated
    ref: 2.5.3
    file: ci-include-node-outdated-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/docker-build
    ref: 6.1.0
    file: ci-include-docker-build-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/sast-container-check
    ref: 2.11.3
    file: ci-include-sast-container-check.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/trivy-container-check
    ref: 2.23.1
    file: ci-include-trivy-container-check-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/container-structure-test
    ref: 2.10.1
    file: ci-include-container-structure-test-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/docker-compose-run
    ref: 3.5.2
    file: ci-include-docker-compose-run.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/push-to-ecr
    ref: 5.0.6
    file: ci-include-push-to-ecr-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/create-project-badges
    ref: 2.5.1
    file: ci-include-create-project-badges-base.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/schedule-creation
    ref: 2.7.4
    file: ci-include-schedule-creation.yml
  - project: dwp/engineering/pipeline-solutions/gitlab/functions
    ref: 7.3.3
    file: functions/auto-tag-merge.gitlab-ci.yml
